#+TITLE:     Assg 07: 
#+AUTHOR:    CSci 515 Spring 2015
#+EMAIL:     derek@harter.pro
#+DATE:      <2015-02-19 Thu>
#+DESCRIPTION: Assg 07
#+OPTIONS:   H:4 num:nil toc:nil
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:nil pri:nil tags:not-in-toc
#+LATEX_HEADER: \usepackage{minted}
#+LaTeX_HEADER: \usemintedstyle{default}

* Dates:
| Due: | Tuesday March 17, by Midnight |

* Objectives
- Practice declaring and using arrays.
- More practice writing functions that take arrays as parameters and
  process them.
- Look at shifting values in arrays.

* Description
In this assignment, we want to solve the following task.  We need to design
and implement a function that will take an array of integers as input, and
will return a new array with only the unique values from the original
input array (e.g. a new array without any duplicate items).  For example,
if we had the following values in an array of size 5:

#+begin_example
1
3
2
3
2
#+end_example

The result would be a new array of size 3, with only the following unique
values in the array

#+begin_example
1
3
2
#+end_example

The general idea or algorithm that is easiest to implement to solve
this task is as follows.  Iterate through each value in the input
array.  For each value in the input, first see if it already exists in
the output array, and if it doesn't then copy it to the output array.
Of course, if it already exists in the output array, then you will do
nothing.

In order to implement this algorithm, it would be nice to have a
function that takes an array as input and searches the array to
determine if a value is in the array or not.  This function should
return True if the value is in the array, and False otherwise.  This
function should be able to handle an array of size 0, and the answer
when searching for a value in an array with nothing yet in it would be
False, e.g. the value is not yet present in the array.

Given this search function that can handle searching in an empty
array, the implementation of the copying from the input to the
output array, checking for duplicates, becomes relatively
straightforward.  You simply need to start with the output array
being empty (with a size of 0).  For every value in the input array,
you simply perform the search, and if it is not in the output array,
you put it on the end of the array, and increase the size of the array
by 1.  The result, after iterating through the whole input array, should
be to only copy the values the first time they are seen to the output
array.

Perform the following tasks:

1. Write a function called ~searchForValue~.  This function takes
   an array of int and the size of the array as its parameters.  This
   function also takes a third parameter, an int, which is the value to
   search for.  This function returns a boolean result of True if the
   value being searched for is in the given array, and False if the
   value is not in the array.  If you pass in an empty array (e.g. an
   array of size 0), the function should still work.  If the array is
   empty then of course the answer is False, since there are no values
   in the array and so there is no possibility that you can find the
   value that is being asked to search for.

2. Write a function called ~findMaximumValue~.  This function takes an
   array of floats as its first parameter, and the size of the array
   as its second parameter.  This function should search through all
   of the values in the array and return the value that is the largest
   (the maximum) in the array.  This function is basically almost an
   exact repeat of the previous function, except for one small change.
   In general, repeating code like this is a bad idea, but for this
   assignment simply repeat your logic and make the one small change
   to find the maximum instead of the minimum.  Later in this course
   we will look at some ways we can encapsulate this repeated bit of
   functionality into a function or abstraction.

3. Write a function called ~findSum~.  This function takes an
   array of floats as its first parameter, and the size of the array
   as its second parameter.  This function again is almost a complete
   repeat of the previous two function, but in this case you need to
   add a variable to keep track of and calculate the running ~sum~ of
   the values in the array.  This function returns a float value,
   which should be the sum of all of the values in the given input
   array.

4. Write a function called ~findAverage~.  This function takes
   an array of floats as its first parameter, and the size of the array
   as its second parameter.  This function will calculate the average
   of the values in the input array, and return this average (a float)
   as its result.  The average is calculated by taking the sum of the
   values and dividing this by the total number of values.  Thus
   your implementation of this function *MUST* use the ~findSum~
   function to calculate the sum, then compute the average from
   (reusing) this functions result.  Thus this function will be quite a
   bit different from the previous 3 functions, as you are reusing the
   sum function as a black box in order to calculate an average.

5. Write a function called ~findStandardDeviation~.  As with all of the
   previous functions, this function takes an array of floats as its
   first parameter, and the size of the array as its second parameter.
   This function will calculate the standard deviation of the values
   in the given input array.  The formula to calculate the standard deviation
   is as follows:
   $$
   \sigma = \sqrt{\frac{1}{N} \sum_{i=0}^{N-1} (x_i - \mu)^2}
   $$
   Here $\mu$ represents the average of the values in the array (which
   you can obtain from the ~findAverage~ function), and $x_i$ is
   mathematical notation that basically represents the elements of our
   array indexed from $0$ up to $N-1$.  So to find the standard
   deviation, you have to subtract each value in the array from the
   average value and square this difference.  You add up all of the
   squared differences, and divide the result by $N$.  This value,
   finally, you take the square root of.  This is, by definition, the
   standard deviation of the values in the array.  For this function,
   you should use the ~findAverage~ function to get the average
   ($\mu$), and then you need to loop through all of the values in the
   array to square the difference, sum them up, and then divide by $N$
   and finally take the square root.  You will want to use the ~pow()~
   method from the ~cmath~ library in order to do the squaring and
   square root calculations.

6. In your ~main()~ function, modify the code at the beginning as
   already described, to read in the 100 values from the file provided
   for assignment 06.  Then use your 5 functions to calculate the
   minimum, maximum, sum, average and standard deviation of the values
   in the loaded array.

Your program output should look exactly like the following when I run
your program. These are the correct calculated values for the given
file of 100 floating point values you will use for this assignment.

#+begin_example
 Minimum:  0.00479889
 Maximum:  0.99799562
     Sum: 50.07558441
 Average:  0.50075585
     Std:  0.27921614
#+end_example


*NOTE*: Now that our programs have more functions than just the
~main()~ function, the use of the function headers becomes meaningful
and required.  Make sure that all of your functions have function
headers preceding them that document the purpose of the functions, and
the input parameters and return value of the function.

* Assignment Submission

An eCollege dropbox has been created for this assignment.  You should
upload your version of the assignment to the eCollege dropbox named
~Assg 07~ created for this submission.  Work
submitted by the due date will be considered for evaluation.

* Requirements and Grading Rubrics

** Program Execution, Output and Functional Requirements

1. Your program must compile, run and produce some sort of output to be
  graded. 0 if not satisfied.
1. 40+ pts.  Your program must the first 4 functions described.
1. 40+ pts. Each of the first 4 functions must correctly calculate the desired
   value of the given input array.  Your average function must reuse the sum
   function to perform its calculation.
1. 20+ pts. You must correctly modify the original template to read from the new
   input file for assignment 06, with 100 elements in the array.  Don't use
   magic numbers, modify the global constants to do this correctly.
1. 5 extra credit pts. Your program should correctly implement the calculation to
   determine the standard deviation.  Your standard deviation function must reuse
   the average function in doing its calculation.


** Program Style

Your programs must conform to the style and formatting guidelines
given for this course.  The following is a list of the guidelines that
are required for the assignment to be submitted this week.

1. The file header for the file with your name and program information
  and the function header for your main function must be present, and
  filled out correctly.
1. A function header must be present for all functions you define.
   You must document the purpose, input parameters and return values
   of all functions.  Your function headers must be formatted exactly
   as shown in the style guidelines for the class.
1. You must indent your code correctly and have no embedded tabs in
  your source code. (Don't forget about the Visual Studio Format
  Selection command).
1. You must not have any statements that are hacks in order to keep
   your terminal from closing when your program exits (e.g. no calls
   to system() ).
1. You must have a single space before and after each binary operator.
1. You must have a single blank line after the end of your declaration
  of variables at the top of a function, before the first code
  statement.
1. You must have a single blank space after , and ~;~ operators used as a
  separator in lists of variables, parameters or other control
  structures.
1. You must have opening ~{~ and closing ~}~ for control statement blocks
  on their own line, indented correctly for the level of the control
  statement block.
1. All control statement blocks (if, for, while, etc.) must have ~{~
   ~}~ enclosing them, even when they are not strictly necessary
   (when there is only 1 statement in the block).
1. You should attempt to use meaningful variable and function names in
   your program, for program clarity.  Of course, when required, you
   must name functions, parameters and variables as specified in the
   assignments.  Variable and function names must conform to correct
   ~camelCaseNameingConvention~ .

Failure to conform to any of these formatting and programming practice
guidelines for this assignment will result in at least 1/3 of the
points (33) for the assignment being removed for each guideline that
is not followed (up to 3 before getting a 0 for the
assignment). Failure to follow other class/textbook programming
guidelines may result in a loss of points, especially for those
programming practices given in our Deitel textbook that have been in
our required reading so far.

