#+TITLE:     Lecture 03 Notes
#+AUTHOR:    Derek Harter
#+EMAIL:     derek@harter.pro
#+DATE:      CSci 515 Spring 2014 <2015-01-28 Wed>
#+DESCRIPTION: Lecture 03 Notes.
#+OPTIONS:   H:4 num:t toc:nil
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:nil pri:nil tags:not-in-toc

* First Session (11 - 11:40)
** Streams
The IOStream library is a new (object oriented) library, added with the C++
language, to support Input and Output to source and destination devices.

The source of input can be a keyboard, a file, or some other device.  Likewise
the destination of output can be to a file, to a terminal screen, or to some
other device (for example you can send output into another C variable, like
a string in memory).

A stream is a way of visualizing how data is transferred from the source to 
destination.  A stream is inherently serial, the order in which you put things
into the stream, is the order they will be received when they come out of the
stream.

** iostream header
You've already seen many examples of specifying the iostream header using

#+begin_src c
#include <iostream>
#+end_src

Iostream operators and objects are defined in the std namespace, thus you
explicitly have to specify ~std::~ before using them, or include the

#+begin_src c
using namespace std;
#+end_src

directive.

In addition to iostream, if you want to do I/O to files, you need to include
the fstream header.  If you want to manipulate and format the data in/out of
the stream, you need to include the iomanip header.

** Standard Stream Objects

- cin, cout input from the standard input device, and output to the
  standard error device respectively.  These are the keyboard and
  terminal, by default, but can be connected to others (like a file)
  by the OS, and program doesn't know or care.
- cerr send output to the standard error device, can be useful for
  separating error messages from normal output (and redirecting
  standard error to a different location).  By default, standard error
  also goes to the terminal.
- clog also connects to the standard error output in a buffered
  manner.  You don't need to be concerned with clog in this class.

** Stream Output and Input

- using the ~<<~ ~>>~  stream notation
#+begin_src c
cout << x << y << z;
cin >> x << y << z;
#+end_src

- Using member functions.  The streams cout, cin, are objects, they have
  member functions.  For example, and put and get single characters:

#+begin_src c
cout.put('A').put('\n');
cin.get(c);
#+end_src

- Example of reading a character at a time of input and echoing until EOF

#+begin_src c
int c; // use int, because char cannot represent EOF
while ( (character = cin.get()) != EOF)
{
  cout.put(character);
}
#+end_src

- Example of reading input a line at a time 

#+begin_src c
const int SIZE = 80;
char buffer[SIZE];

cin.getline(buffer, SIZE);
#+end_src

- peek, putback and ignore can be used for low level I/O.  We can
  ignore a number of characters, and we can peek ahead (without
  reading) or putback a character into the stream.

** Formatted I/O, Precision and float output

- We can display integers in any base,  using hex, oct, dec and setbase()
- For float/double types, use cout.precision(p) or setprecision(p) 
  manipulator to set number of decimal places shown.
- For float/double, you can force fixed or scientific notation output
  using those output stream manipulators.

** Field width

- For strings (both inputs and outputs) can limit output using
  cxx.width(w) or the setw(w) io manipulator.

** Other Formatting

- Figure 15.12 in section 15.7 shows a lot of other useful manipulators,
  including to show as uppercase or lowercase, skipping white-space on input,
  show or don't show the base for integers, etc.

** Left and right justify strings, padding
- use left and right manipulators to justify a sting output in a field.  
- needs to be used in conjunction with setw(w) manipulator normally.
- Can pad out strings (instead of using whitespace when justifying)
  by using setfill('x')

** Boolean output representation
- Can have booleans output as true/false (rather than 0/1) using boolalpha
  manipulator.



* Second Session (11:45 - 12:30)

** File Processing
For the most part, all of the stream I/O we have seen can be done to
and from a file that you open and specify (instead of the standard
input/output device).  This is more complicated for a binary file we
want to randomly access, but we will first look at opening a plain
text stream, and reading/writing it sequentially.

** Creating a Sequential File

- need to include fstream libray to open files for read/write
- At most basic, can open a file for output as

#+begin_src c
ofstream outFile("name-of-output-file.txt");
#+end_src

- And can open a file for input using:

#+begin_src c
ifstream inFile("name-of-input-file.txt");
#+end_src

** Writing/Reading Data from a sequential File

- An open output stream file using sequential access, can be written
to using the name we just created.  For example:

#+begin_src c
outFile << x << y << z;
#+end_src

- Likewise we can read input from a simple sequential file we opened:

#+begin_src c
inFile >> x >> y >> z;
#+end_src

- HINT: You need to be careful that you know what file you are opening
  and where it is located on your filesystem.  I require that you
  always check whether the open of the file was successful after
  opening it:

#+begin_src c
ofstream outFile("name-of-input-file.txt");

// exit program if unable to create a file
if (!outFile)
{
  cerr << "File name-of-input-file.txt could not be opened, file not found error." << endl;
  exit(1);
}
#+end_src

- Also, never hardcode an absolute path to a file.  Always use a relative path name.
- Once you successfully open a file for read/write, you can use any of
  the iostream methods we have talked about to format the input/output
  from/to the file.

** Reading Lines of Data from a File
** Reading comma separated values (CSV)
** Random Access Files
- Create using ios::binary specifier
- use seekp() and write() read() member functions to get data in and out.
- seekp() need to specify a byte location to move to in file, need to
  calculate correctly or bad things will result.
- Advantages of binary files, more compact, faster to access (because of this)
- But overrated.  Plain text files are human readable and editable.
  Storage is cheap, programmer time is expensive.

* Third Session (12:40 - 1:40)

** 


