* Index

| Sep 04 | 01 | Intro to Variables                |
| Sep 11 | 01 | MinMax                            |
| Sep 12 | 01 | Geometry                          |
| Sep 13 | 01 | Static Cast                       |
| Sep 17 | 01 | Store                             |
| Sep 20 | 01 | Compound Statements               |
| Sep 24 | 02 | MaxFinder                         |
| Sep 25 | 02 | MinMaxChars                       |
| Sep 27 | 01 | NumberGame                        |
| Oct 01 | 02 | Substring Finder                  |
| Oct 02 | 03 | Function Definitions              |
| Oct 07 | 03 | Spelling Out Dates                |
| Oct 10 | 02 | RandCalculation                   |
| Oct 15 | 03 | Function Overloading              |
| Oct 17 | 03 | Date Calculator                   |
| Oct 22 | 05 | Char Frequency                    |
| Oct 25 | 05 | Mix of Numbers and Chars          |
| Oct 22 | 05 | Char Frequency                    |
| Oct 29 | 05 | Stats in 2D Array                 |
| Nov 02 | 05 | Sorting                           |
| Nov 05 | 06 | Phone Keys                        |
| Nov 06 | 06 | Struct with Functions             |
| Nov 07 | 05 | Logo                              |
| Nov 07 | 05 | Dim Converter                     |
| Nov 12 | 06 | Absolute Frequency                |
| Nov 21 | 07 | Word Hunter                       |
| Nov 23 | 06 | Sorted Structs                    |
| Jan 27 | 01 | Assignment 0                      |
| Feb 11 | 02 | Math in File                      |
| Feb 28 | 01 | Random Math                       |
| Mar 25 | 03 | Spelling Out Numbers              |
| Mar 28 | 03 | Month Calculator                  |
| Apr 03 | 07 | Arrow Operator (Intro to Pointers |
| Apr 11 | 05 | Hotel Manager                     |
| Apr 26 | 06 | Cricket World Cup                 |

* 01 Basic Elements of C++

** Assignment #0
Assignment #0

Due date: 11:59pm, Tuesday  Januray 27, 2015

You will earn 100 points if you return complete and in time. You will lose 20 points for each late hour. You need to upload your assignment through eCollege system. You should upload a file named Assg_0.cpp (not a .txt or .exe  file).

Objective: In this assignment, you need to demonstrate basic data types of C++.

Write a complete C++ program that uses all nine integral data type involving a math operation (one of +, -, /, *) using a same kind hard-coded value. Only one operation is enough. For instance, to demonstrate the unsigned integer:

unsigned int first = 33; 

first = first + 5; // here first and 5 are both unsigned integers.


Your code should start with comments as follows:
// FIRSTNAME LASTNAME  - Jan 27, 2012

// CWID: 123456789

// Compiler: Visual Studio

// Assignment #1 

/* This program calculates … or This function takes two int parameters ….

Summarize your code functionality here.       

*/

Dropbox Assignment Submission Procedures

To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled Assignment #0. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


** Static Cast
Static Cast

Due date: Friday, Sep 13, 11:59pm.

You will earn 100 points if you return complete and in time. You will lose 50 points for each late day (24 hour).

You need to upload your assignment through eCollege system. You should upload a file named StaticCast.cpp.

Objective: In this assignment, you need to demonstrate basics of C++

Write a complete C++ program that shows explicitly cast (using static_cast) operator

 an integer variable to double. Print new double number on the screen
 a short variable to integer. Print new integer number on the screen
 a unsigned char to double. Print new double number on the screen
Tip:

Don’t use unnecessary libraries. You may use lose points because of calling unused libraries.

Your code should start with comments as seen in following:

// FIRSTNAME LASTNAME  - May 30, 2033

// CWID: 123456789

// Compiler: Visual Studio

// Assignment #1 

/* This program calculates … or This function takes two int parameters ….

Summarize your code's functionality here.       

*/

Dropbox Assignment Submission Procedures

To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled Static Cast. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


** Geometry
Geometry
Due date:  Friday, 9/12, 11:59pm.

You will earn 100 points if you return complete and in time. You will lose 50 points for each late day (24 hour).

You need to upload your assignment through eCollege system. You should upload a file named Geometry.cpp.

Objective: In this assignment, you need to demonstrate basics of C++.

Write a complete C++ program that takes width and height of a rectangular and calculates its area and perimeter. The user will input height and width as (signed or unsigned? ) integers. The results should be printed out to screen. Also give a message if user entered the measures (width/height) for a square. See below for example output.

> Enter width and height of rectangle: 3 5

> Area:15, perimeter:16


> Enter width and height of rectangle: 9 9

> Area:81, perimeter:36. It is a square.

Tip(s): 
Don’t use unnecessary libraries. You may use lose points because of calling unused libraries.

Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - DATE
// CWID: YOUR_ID
// Compiler: NAME_OF_COMPILER
// Assignment  ID
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.       
*/
Dropbox Assignment Submission Procedures
To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled same as assignment ID (Geometry). Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


** Intro to Variables
Intro to Variables
Due date: Wed, Sep 4, 11:30am.
You will earn 100 points if you return complete and in time. You will lose 30 points for each late hour. You need to upload your assignment through eCollege system. You should upload a file named Assg_1.cpp.
Objective: In this assignment, you need to demonstrate basics of C++.
Write a complete C++ program that prints out result of four math operations (+,-,*,/) within a cout operator, such as cout <<  2 + 2; for addition. In addition, printout first three characters of your last name on screen using ASCII table value. Assuming your last name is "TEST". So, write
char first = 84; // 84->T
char second = 69; // 69->E
char third = 83; // 83->S
cout << "My last name starts with " << first << second << third <<  "." ;

Your code should start with comments as follows:
// FIRSTNAME LASTNAME  - Jan 27, 2010
// CWID: 123456789
// Compiler: Visual Studio
// Assignment #1 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.       
*/
Dropbox Assignment Submission Procedures
To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled Intro to Variables. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.



** Store
The Store
Due date: Wed, 9/17, 11:59pm.
You earn 100 points if you return complete and in time. You will lose 10 points for each late hour.
You need to upload your assignment through eCollege. You should upload a file named Store.cpp.
Objective: In this assignment, you need to demonstrate your ability in input, output, data types, and if statement.
Assume that you need write a C++ program for a cash register. There are only three items in the store:

Bread, $0.99 each
Milk, $3.99 each
Banana, $ 0.77 each

Once a customer buys items, you will ask her/his how many of them are bought. The quantity can be in the range of 0-10 (including 0 and 10).

Then, calculate total for this transaction. Later ask for payment method, which could be either Credit Card or Cash. 

If the payment method is CC, your program exits. If it is cash, and enter the amount received from customer. Then show the due amount the customer.

An example scenario for a CC payment would be:

Enter how many bread customer bought:2
Enter how many milk customer bought:1
Enter how many cheese customer bought:3

Total is $8.28

Payment Method:CC

Thanks...

An example scenario for a cash payment would be:

Enter how many bread customer bought:2
Enter how many milk customer bought:1
Enter how many cheese customer bought:3

Total is $8.28

Payment Method:Cash

Enter the amount received from customer:25.00

Due amount is $16.72

Thanks...

Tip:
Don’t use unnecessary libraries. You may use lose points because of calling unused libraries.
Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - Sep. 17, 2014
// CWID: 123456789
// Compiler: Visual Studio
// Assignment Store 
/* This program calculates … takes two int numbers ….
Summarize your code functionality here.       
*/
 dropbox01Dropbox Assignment Submission Procedures
To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled Store. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


** Compound Statements

Compound Statements

Due date: Friday, Sep 20, 11:59pm.

Assignment Type: Individual, meaning that extremely similar or same assignment will result in course grade F.
Grade: You will earn 10 points if you return your assignment complete and in time. You will lose  points for each late day (60 min).
Submission: You need to upload your assignment through eCollege system. You should upload a file named Compound.cpp.
Objective: In this assignment, you need to demonstrate conditional selection and a basic loop.
Description:In this assignment, you need to demonstrate your ability in changing flow of execution. 

What is this month? Possible answers: January, February, ... , December
What is today? Possible answers: Monday, Tuesday, ... , Sunday
Do you take CSCI 515? Possible answers: Yes, No

Based on answers you get, if user takes CSCI 515; and today is Tuesday or Wednesday or Thursday; and the month is not May, June, July, August (summer) then print a message "You have 515 class today". If it is not a summer month, and it is a weekday but not Tuesday or Wednesday or Thursday, print a message "Study 515 at home today." If it is weekend, just print a message "Have a nice weekend.". If it is summer, print a message "Have a nice summer.". For all other cases, print "Enjoy your day!!!".

You should use at least one compound logical expression in if statement, i.e, if ( .... && ....), if ( .... || ....), if ( .... || .... && .....).


Don’t use unnecessary libraries. You may use lose points because of calling unused libraries.
Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - Jun 28, 2012
// CWID: 123456789
// Compiler: Visual Studio
// Assignment #4
/* This program calculates … takes two int numbers ….
Summarize your code functionality here.       
*/
 dropbox01Dropbox Assignment Submission Procedures
To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled CompoundStatements. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


** MinMax
MinMax

Due date: Wednesday, Sep 11, 11:30pm.

You earn 100 points if you return complete and in time. You will lose 30 points for each late hour.

You need to upload your assignment through eCollege system. You should upload a file named MinMax.cpp.

Objective: In this assignment, you need to demonstrate basics of C++

Write a complete C++ program that shows initialization of nine different integral data types, which were discussed in class. First you need initialize one variable for each data type. With each variable, comment out memory size of it. After initializing, you should assign minimum and maximum values to those variables. Check your compiler specs to find out minimum and maximum values regarding data types. Then, you should print out minimum and maximum values of variables on screen.

For instant, your code may include

int i_typ; //  four bytes

i_type =  123; // max of int

cout <<  “Max int:” << i_type << endl ;

Tip:
Don’t use unnecessary libraries. You may use lose points because of calling unused libraries.

Your code should start with comments as seen in following:

// FIRSTNAME LASTNAME  - Jan 27, 2010

// CWID: 123456789

// Compiler: Visual Studio

// Assignment #1 

/* This program calculates … or This function takes two int parameters ….

Summarize your code functionality here.       

*/

To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled MinMax. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


** NumberGame 
NumberGame

Due date: Friday, Sep 27, 11:59pm.

You earn 100 points if you return complete and in time. You will lose 30 points for each late day.

You need to upload your assignment through eCollege. You should upload a file named NumberGame.cpp.

Objective: In this assignment, you need to demonstrate your ability in  while loop, switch structure, and other basic of C++.

You aim to write a program to play number guessing game, as discussed in this week lecture. It is game played by two persons. One (Person A) pick a secret number in a number range, such as 1-100, then other (Person B) tries to guess the secret number. When Person A hears a new number from Person B, he/she says only one of these three options:"too high", "too low", or "yes, it is correct."

In you program, there will be two scenarios: 
1) Computer picks a number and user tries to find secret number.
2) User picks a number and computer tries to find user's secret number.

First design a menu:

Select number range:
1) 1-10
2) 1-20
3) 1-50
4) 1-100

Then show a second menu

Select playing scenario :
1) Computer keeps a number and user finds it
2) User keeps a number and computer finds it

Based on selections, the game starts.  After the game is over, you will ask if user wants to play again or not. If yes, then restart game.

The two menus will be written in switch structure. You will need to use random function, rand(). Please see example program at  http://codepad.org/ZCryJ3WY 

Please submit your cpp file to dropbox: NumberGam

** Random Math
Random Math Operations 

Due date: Friday, Feb 28, 11:59pm.

You earn 100 points if you return complete and in time. Late submissions will be not accepted.

You need to upload your assignment through eCollege. You should upload a file named RandomMath.cpp. 

Description: This program is to ask the user N number of math (using only +, -, *, and /) questions. Once the program start it asks the user to enter how many questions will be asked (N, which is between 3-30, including). Then, the program automatically asks N questions. Each question will be one of four math operations (+, -, *, and /).  The operation and operands will be selected randomly in your program.
After N questions, program exits with success score. The operands can be only “unsigned short”. See a sample run.

------

Enter number of questions: 5

3 + 4 = 6
Incorrect, 7 was the answer.

8 – 4 = 4

Correct

5 * 6= 30

Correct

5-345= -300

Incorrect, -340 was the answer

0-0=0

Correct

Your success rate is 60%.


-----
Your code should start with comments as follows:

// FIRSTNAME LASTNAME  - Feb 20, 2014

// CWID: 123456789

// Compiler: Visual Studio

// Assignment: Random Math 

/* This program  does ...

Summarize your code functionality here.       

*/

Dropbox Assignment Submission Procedures

To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled RandomMath. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


* 02 File IO, Loops

** RandCalculation
RandCalculation



Due date: Saturday, 10/5, 11:59pm

Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late day (24 hour).

Submission: You need to upload your assignment through eCollege system. You should upload a file named RandCal.cpp.

Objective: In this assignment, you need to mainly demonstrate  loops, file operations, and predefined function(s), especially random.


Description

You will be given a *.txt file, similar to  Random_Calculation.txt in Doc Sharing. The file has two numbers at each line. Notice that number of operation in the file is not known. You need to write your program to find a random operation (from the set of plus, minus, times, divided by, mod, power ) for each line, then calculate the operation and write this operation into another file with results.

For instance, the input file has only three lines,

12 56
9 -3
45 15 

You will run your program and find an operation for each line iteratively using rand() function. Assuming you found randomly first minus, then divided by and plus, your output file will be

12 minus 56 is -44
9 divided by -3 is -3
45 plus 15 is 65


An example for rand() function is given at http://codepad.org/ZCryJ3WY . The name of output file will be operations.txt. 

Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - Feb 3, 2010
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment ??
 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.
  
*/
int main()
{}
Dropbox Assignment Submission Procedures

To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled RandCalculation. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.



** MinMaxChars
 
Min-Max Chars of File

Due date: Wednesday, Sep. 25, 11:59pm

Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late hour. 

Submission: You need to upload your assignment through eCollege system. You should upload a file named MinMaxChars.cpp. 

Objective: In this assignment, you need to mainly demonstrate loops and file IO operations.

Description

Assume that you have a text file, letters.txt that have only one character in each line.

C
G
T
+
M
m
r
6
9
R

You will write a program to find minimum and maximum of characters (according to ASCII table) given in the file.

Keep in mind:
Number of lines in the file can be as much as possible.
Do not predefine a minimum and maximum values. Instead the first char of the file will be min and max.
Think about extreme cases: Many characters or only one character in the file.

Choose your loop carefully. 

    Don’t use unnecessary libraries.
    You may use lose points because of calling unused libraries.
Commenting in appropriate way will be evaluated. 

Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - Feb 3, 2010
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment #3
 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.
  
*/
int main()
{}
Dropbox Assignment Submission Procedures


To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled MinMaxChars. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


** MaxFinder

 MaxFinder

Due date: Wednesday, 9/24, 11:59pm

Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late hour. 

Submission: You need to upload your assignment through eCollege system. You should upload a file named MaxFinder.cpp. 

Objective: In this assignment, you need to mainly demonstrate loops, assert function, and  and other logical operators. 


Description

In this program, you will ask user to enter a positive integer number, N, between 4 and 8 (including 4 and 8). This number indicates how many numbers user will enter into your program.  Then in a loop, ask user N times to enter a number. At each time, user will enter one number only. At the last, your program prints out maximum of all entered number.

How many numbers do you want to enter:4
Enter a number: 3
Enter a number: 33
Enter a number: 333
Enter a number: 99
The maximum of them is 333

Additional Conditions: 
Use assert function to make sure that N is between 4 and 8. See  http://codepad.org/55znhRl2  for an example usage.
Use ternary operator to find maximum of two numbers, such as max_n = (max_n<new_n) ? new_n : max_n ; 

Don’t use unnecessary libraries. 
You may use lose points because of calling unused libraries.
Commenting in appropriate way will be evaluated. 

Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - Feb 3, 2055
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment #3
 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.
  
*/
int main()
{}
Dropbox Assignment Submission Procedures


To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled MaxFinder. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.



** Math in File
Math in File



Due date: Monday, 2/11, 11:59pm

Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late day (24 hour).

Submission: You need to upload your assignment through eCollege system. You should upload a file named MathInFile.cpp.

Objective: In this assignment, you need to mainly demonstrate  loops and file operations.


Description

You will be given a *.txt file, similar to OpeInFile.txt in Doc. Sharing. The file has only one calculation per line. Notice that number of lines in the file is not known. You need to write your program to read each line and write the question and answer into another line.
There are six main math operations: plus, minus, times, divided by, Min, Max. However plus, minus, times, and divided by can be expressed with signs also. 
For instance, the input file has only three lines,

12 + 56
9 divided by -3
45 minus 15
Min of 2 and 1
Max of 3 and 5
34 plus 33

  Your output file will be

12 + 56 is 68
9 divided by -3 is -3
45 minus 15 is 30
Min of 2 and 1 is 1
Max of 3 and 5 is 5
34 plus 33 is 67


The name of output file will be OpeResults.txt. 

       Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - Feb 3, 2010
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment ??
 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.
  
*/
int main()
{}

** Substring Finder
Substring Finder
Due: Wednesday, Oct 1st, 11:59pm
Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late day (24 hour).
Submission: You need to upload your assignment through eCollege system. You should upload a file named substring.cpp. 
Description
You will develop a C++ program to find a frequency of substring in strings of a txt file. Once you run your program, it will ask the user the input file and substring (see below for an example run). Then the program searches the substring in file and outputs frequency of the substring. A substring has at least two characters.

Enter file name: test.txt
Enter a substring to find:ing
Found 33 "ing" in test.txt.

Do you want to search another substring(y/n):y
Enter a substring to find:sh
Found 55 "sh" in the test.txt.


In this program you have to implement a function that takes a string and a substring then return frequency of substring in string as unsinged short. The function signature will be 
unsigned short NumStr(string mainstr, string user_substr);


You will use <string> library in this program. Also you can use predefined functions from <string> such as substr() and find(). Please check documentation of string library to find functions you need to use.

Don’t use unnecessary libraries.
You may use lose points because of calling unused libraries.
Commenting in appropriate way will be evaluated.
Your code should start with comments as seen in following:

// FIRSTNAME LASTNAME - Feb 3, 2034

// CWID: 123456789

// Compiler: Visual Studio, GNU C++, etc.

// Assignment ...



/* This program calculates … 

*/

int main()

{}

Dropbox Assignment Submission Procedures

To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled Substring Finder. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.





* 03 Functions I

** Function Definitions
Function Definitions


Due date: Wednesday, Oct 2, 11:30am

Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late hour. 

Submission: You need to upload your assignment through eCollege system. You should upload a file named FunDef.cpp. 

Objective: In this assignment, you need to mainly demonstrate concepts of function definition. 


Description

In a program, define a set of functions to complete following operations.

max_of(int, int, int) returns maximum of three integers.
max_of(short, short, short) returns maximum of shorts. 
sumall(int, int &, short, short &) returns sum of all integers and shorts.
addS(string, string) returns concatenation of two strings.
IsIn(string, char) returns true if char is found in string. Returns false if not. You can use other string function(s) in this function.

Give example usages for each function in the main the function.
Don’t use unnecessary libraries. 
You may use lose points because of calling unused libraries.

Commenting in appropriate way will be evaluated. 

Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - Feb 3, 2010
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment #9
 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.
  
*/
int main()
{}

Dropbox Assignment Submission Procedures

To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled FunDefinitions. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.

** Spelling Out Numbers
Spelling Out Numbers
Due date: Tue, Mar 25, 11:59pm
Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late day (24 hour).
Submission: You need to upload your assignment through eCollege system. You should upload a file named Spellout.cpp.
Objective: In this assignment, you need to demonstrate mainly file operations, loops, string operations, and user defined functions (optional).
 Description
You will develop a C++ program to spell out numbers given in a file. Assume that you have text file appears as

15
-568
3432
9001
16045
...
...

Input file has one number (short) (minus or plus or zero) at each line. A number can have at most 5 characters, such as 12356, or  -1245. For the above file, your program should generate 

fifteen
minus  five hundred sixty eight 
three thousand four hundred sixty two
nine thousand one
sixteen thousand forty five
...
...


While completing your assignment, write a function takes an short, which is a number read from file, and returns a string, which is spelling out  of number, i.e., the prototype seems like

string Spell (short a);

Note that you do not know how many numbers are in the input file. See  http://codepad.org/IZ9UbWji for a clue.

Notes:
Don’t use unnecessary libraries. You may use lose points because of calling unused libraries.
 Your code should start with comments as seen in following: 
// FIRSTNAME LASTNAME  - Mar 25, 2099
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment
 
/* This program calculates or This function takes two int parameters
Summarize your code functionality here.
  
*/
int main()
{
 
}
 
Commenting in appropriate way will be evaluated. You may lose 1 (one) point if you don’t comment out your code appropriately.
 
Dropbox Assignment Submission Procedures
To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled SpellingOutNumbers. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.

** Function Overloading
Function Overloading

Due date: Wednesday, Oct 15, 11:59pm

Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 50 points for each late hour. 

Submission: You need to upload your assignment through eCollege system. You should upload a file named FuncOver.cpp. 

Objective: In this assignment, you need to mainly demonstrate function overloading concept. 


Description

In a program, define a set of functions to complete following operations.

Nbits(float) returns number of bits use this float variable, which is sizeof(float) * 8.
Nbits(bool) returns number of bits use this bool variable, which is sizeof(bool) * 8.
Nbits(unsinged double) returns number of bits use this unsigned double variable, which is sizeof(unsigned double) * 8.
Cube(unsigned short n) returns n*n*n.
Cube(unsigned float n) returns n*n*n.

Give example usages (function calls) for each function in the main the function.
Don’t use unnecessary libraries. 
You may use lose points because of calling unused libraries.

Commenting in appropriate way will be evaluated. 

Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - Feb 3, 2010
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment #9
 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.
  
*/
int main()
{}

Dropbox Assignment Submission Procedures

To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled Function Overloading. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.

** Date Calculator
Date Calculator

Due date: Thursday, Oct 17, 11:59pm

Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late day (24 hour).

Submission: You need to upload your assignment through eCollege system. You should upload a file named DateCalc.cpp.

Objective: In this assignment, you need to demonstrate mainly file operations, loops, string operations, and user defined functions.

 Description

You will develop a C++ program for date calculation which is specified in a text file. Assume that you have text file, which appears as

01-01-1976  to 05-05-2013
01-01-2006 + 100
05-12-2008 - 300
02-27-2011 to 01-01-2005 
...
...
...

The format of each line can be one of three:
Date to Date
Date - number of days
Date + number of days

Date format is Month-Day-Year

"Date to Date" means you need to calculate difference between two dates in days, such as 01-01-1976 to 05-05-2013 should yield 13639 (days).
Date + N, means you need to add N days to the date, and find a new date. 01-01-2006 + 100 should yield 04-11-2006.
Date - N, means you need to subtract  N days from the date, and find a new date. 01-01-2006 - 300 should yield 07-17-2007.

Notice that Date to Date operation can have (earlier to later) or (later to earlier) format. Earlier to later  results in positive number, as given above example. However, later to earlier gives a negative results, such as 02-27-2011 to 01-01-2005 should yield -2248 (days).

In the text file, N is positive integer and N<30000.

Since essentially there are three operations in the text file, (from, add, subtract) write three functions to accomplish these tasks. Your functions should take required parameters and return a string as a results. You should print it on screen for each calculation (line) given in the text file. The input file can have many lines, as assumed by default.

Tip: MS Excel has similar calculations already. You may validate your results using Excel.

Notes:
Don’t use unnecessary libraries. You may use lose points because of calling unused libraries.

 Your code should start with comments as seen in following: 

// FIRSTNAME LASTNAME  - Sep 8, 2009

// CWID: 123456789

// Compiler: Visual Studio, GNU C++, etc.

// Assignment #7

 

/* This program calculates or This function takes two int parameters

Summarize your code functionality here.

  

*/

int main()

{

 

}

 

Commenting in appropriate way will be evaluated. You may lose 10 (one) point if you don’t comment out your code appropriately.

Dropbox Assignment Submission Procedures

To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled DateCalculator. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


** Month Calculator
Month Calculator

Due date: Friday, March 28, 11:59pm

Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late day (24 hour).

Submission: You need to upload your assignment through eCollege system. You should upload a file named MonthCalc.cpp.

Objective: In this assignment, you need to demonstrate mainly file operations, loops, string operations, and user defined functions.

 Description

You will develop a C++ program for date calculation which is specified in a text file. Assume that you have text file, which appears as

Jan 1  to May 5
Jan 1 + 100
May 12 - 300
Mar 4 + 10
Dec 31 - 55
Feb 23 to Jan 23
.

The format of each line can be one of three:
Month Day to Month Day
Month Day + number of days
Month Day - number of days


"Date to Date" means you need to calculate difference between two dates in days, such as Jan 1  to May 5  should yield 124 (days), because starting Jan 1 124 days later falls into May 5.
Date + N, means you need to add N days to the date, and find a new date. Jan 1 + 100 should yield Apr 11. 
Date - N, means you need to subtract  N days from the date, and find a new date. Jan 1 - 300 should yield Mar 7.

Assume that February has 28 days always.

In the text file, N is positive integer and N<=366.

Since there are three operations in the text file, (from, add, subtract) write three functions to accomplish these tasks. Your functions should take required parameters and return a string as a results. You should print it on screen for each calculation (line) given in the text file. The input file can have many lines, as assumed by default.

Tip: MS Excel has similar calculations already. You may validate your results using Excel.

Notes:
Don’t use unnecessary libraries. You may use lose points because of calling unused libraries.

 Your code should start with comments as seen in following: 

// FIRSTNAME LASTNAME  - Sep 8, 2009

// CWID: 123456789

// Compiler: Visual Studio, GNU C++, etc.

// Assignment Month Calculator

 

/* This program calculates or This function takes two int parameters

Summarize your code functionality here.

  

*/

int main()

{

 

}

 

Commenting in appropriate way will be evaluated. You may lose 10 (one) point if you don’t comment out your code appropriately.

Dropbox Assignment Submission Procedures

To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled MonthCalculator. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.



** Spelling Out Dates
Spelling Out Dates
Due date: Tue, Oct 7, 11:59pm
Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late day (24 hour).
Submission: You need to upload your assignment through eCollege system. You should upload a file named Spelloutdates.cpp.
Objective: In this assignment, you need to demonstrate mainly file operations, loops, string operations, and user defined functions (optional).
 Description
You will develop a C++ program to spell out numbers given in a file. Assume that you have text file appears as

5/3/2014
12-4-2011
01-19-200
1/1/2011
03/03/1900
...
...

Input file has one data at each line. Notice that month, day, and year of date can be seperated by '/' or '-'. For the above file, your program should generate 

May 3rd, 2014
December 4th, 2011
January 19th, 200
January 1st, 2011
March 3rd, 1900
...
...


While completing your assignment, write a function takes a string, which is a date from the file, and returns a string, which is spelling out  of number, i.e., the prototype seems like

string Spell(string a);


Notes:
Don’t use unnecessary libraries. You may use lose points because of calling unused libraries.
 Your code should start with comments as seen in following: 
// FIRSTNAME LASTNAME  - Mar 25, 2029
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment
 
/* This program calculates or This function takes two int parameters
Summarize your code functionality here.
  
*/
int main()
{
 
}
 
Commenting in appropriate way will be evaluated. You may lose 10 points if you don’t comment out your code appropriately.
 
Dropbox Assignment Submission Procedures
To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled SpellingOutDates. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


* 04 Functions II

* 05 Arrays

** Mix of Numbers and Chars
Mix of Numbers and Chars
Due date: Friday, Oct 25, 11:59pm

Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late day.

Submission: You need to upload your assignment through eCollege system. You should upload a file named MixIntChar.cpp.

Objective: In this assignment, you need to mainly demonstrate your ability in using arrays.


Description

Assume that you are given a text file, which can contain up to 200 integer numbers and 200 characters. 

12 a -5 
T 23 -1 34 R K s 3 4 r  
a a 34 12 -12 y  

As seen in above representation, each line can have multiple numbers.  Your task is write a program to find

- How many lower case letters given in the file
- How many upper case letters given in the file
- How many integers given in the file
- Sum of all integers in the file

You should keep all integers in an array, and characters in another array. Think about extreme cases and decide about size of arrays.

Your program should output similar to:

10 numbers are found in the file. The sum is 104.
6 lower case letters and 3 upper case letters are found in the file.

You should use an array / arrays with reasonable initial capacity. You may implement your program using parallel arrays.
Don’t use unnecessary libraries, you may use lose points because of calling unused libraries.
Commenting in appropriate way will be evaluated.

Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - Feb 3, 2010
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment #3
 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.
  
*/
int main()
{}

To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled MixIntChars. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.

** Char Frequency
CharFrequency
Due date: Wed, Oct 22, 11:59pm. Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late day.

Submission: You need to upload your assignment through eCollege system. You should upload a file named CharFrequency.cpp.

Objective: In this assignment, you need to mainly demonstrate your ability in using parallel arrays.


Description

Assume that you are given a text file, which can contain up to 200 letters from the set of {A, B, C, D, E}, such as

A E  
B B A A D E A A
C C D D D D D


In the data file, number of letters in one line can be different than others. Write a C++ program to find 
1) Frequency of each letter
2) The most and the least frequent letters.

For the above example, the output should be

A -> 5
B -> 2
C -> 2
D -> 6
E -> 2
The most frequent letter(s) seen 6 time: D
The least frequent letter(s) seen 2 times: B, C, E

You should use an array / arrays with reasonable initial capacity. 
Don’t use unnecessary libraries, you may use lose points because of calling unused libraries.
Commenting in appropriate way will be evaluated.

Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - Feb 3, 2010
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment #3
 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.
  
*/
int main()
{}
 
Dropbox Assignment Submission Procedures

To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled Arrays:CharFre. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.

** Stats in 2D Array


Statsin2DArray
Due date: Wed, Oct 29, 11:59pm

Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 20 points for each late hour. 

Submission: You need to upload your assignment through eCollege system. You should upload a file named Statsin2DArray.cpp .

Objective: In this assignment you need to demonstrate your skills in multidimensional arrays

Description

 You need to write a programs which fills a 3x7 array with random numbers between 20 and 50 (including 20 and 50). Find

- Mean of all 21 numbers in the array
- Max of all 21 numbers in the array
- Min of all 21 numbers in the array
- Frequency of all numbers in the array
- Standard deviation of numbers in filled 2D array

Refer to  http://codepad.org/ZCryJ3WY  for a random number generator example.

Use Std. Dev. No Image , N is number of data points, which is 21 in this program.  No Image is mean of the list.

You can use predefine functions, such as pow() and sqrt().

Notes:

Don’t use unnecessary libraries. You may use lose points because of calling unused libraries.
Commenting in appropriate way will be evaluated. You may lose 10 (one) point if you don’t comment out your code appropriately.   
Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - March 8, 2010
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment #6
 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.
  
*/
int main()
{
 
}
      

dropbox01Dropbox Assignment Submission Procedures
To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled Statsin2DArray. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


** Logo
TAMU-C Logo
Due date: 11:59pm, Fri, Nov. 7
Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 20 points for each late day (24 hour).
Submission: You need to upload your assignment through eCollege system. You should upload a file named Logo.cpp (not a txt, exe, or doc file).
Objective: In this assignment you need to demonstrate your skills in 3D array representation, abstraction and manipulation.

Description 

Download Tamu-commerce_logo-pixels.zip  from Doc Sharing section of this course. This zip file includes Logo_red.txt, Logo_green.txt, Logo_blue.txt files, which are color layer of our university's spirit logo, Lion. The image has size of 86x86 pixels. A pixel is unit size in image, and composed of 3 bytes (red, green, blue).

You responsibilities includes followings:

Define and initialize a 3D array to keep RGB pixels structured.
Read pixels from three different files into your 3D array.
Find average values for each layer R (red), G (green), B (blue) (Array[i][j][0] + Array[i][j][1]  + Array[i][j][2] ) /3, which is called intensity of a pixel.
Find maximum and minimum intensity pixels of the image. Also, print out those pixel addresses of min an max values. Intensity is average of R, G, and B values. In case of multiple minimum and maximum values, you should show all of the pixel locations. 
List address (x, y location) of pixels meeting pixel.R < pixel.G 
Constrains: You need to read each source file once.

Details of the homework will be discussed in the class on Monday. 
Notes:

Don’t use unnecessary libraries. 
Commenting in appropriate way will be evaluated. You may lose 1 (one) point if you don’t comment out your code appropriately.   
Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - Sep 8, 2009
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment #9
 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.
  
*/
int main()
{
 
}
      

dropbox01Dropbox Assignment Submission Procedures
To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled Assignment #13. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


** Dim Converter
DimConverter
Due date: 11:59am, Wed

Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late hour. 

Submission: You need to upload your assignment through eCollege system. You should upload a file named DimConverter.cpp. 

Objective: In this assignment you need to demonstrate your skills in 2D arrays especially.

Description

You need to write a programs (especially functions) to converts 2D  to 1D, and vice versa. The major constraint is that you should not use any global variable in your program. The steps are given below.

Define a function (say F_2D_1D) takes 2D array and 1D array as two parameters. This function converts 2D array into 1D array organization. For instance, if the 2D array is 
3 5 6 5
5 6 7 0
. . . . 
. . . .
1 2 3 4

then 1D array should be filled as  3 5 6 5 5 6 7 0 . . . . . . . . 1 2 3 4. You should insert data from 2D array into 1D array row-by-row.
Define a function (say, F_1D_2D) takes 1D array and 2D array as two parameters.  This function reads values from 1D array and store them in a 2D array. This function does reverse operation of F_2D_1D.
In the main function, create a 2D array having 4 rows and 5 columns  with random unsigned short values between 1-9999. Then convert it to 1D using F_2D_1D. Print out input and output arrays in the main function.

In the main function, create a 1D array having 60 elements with random unsigned short values between 1-9999. Then convert it to 2D (10-by-6) using F_1D_2D. Print out input and output arrays in the main function.

Notes:

In your functions, you may assume that sizes of array are known.
Don't use global variables.
Don’t use unnecessary libraries. You may use lose points because of calling unused libraries.
Commenting in appropriate way will be evaluated. You may lose 10 points if you don’t comment out your code appropriately.  
Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - March 8, 2010
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment #6
 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.
  
*/
int main()
{
 
}
      

dropbox01Dropbox Assignment Submission Procedures
To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled DimConverter. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


** Sorting
Sorting


Due date: 11:59pm, Saturday, Nov 2nd

Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late day (24 hour).
Submission: You need to upload your assignment through eCollege system. You should upload a file named Sort.cpp.
Objective: In this assignment you need to demonstrate your skills in sorting and searching on an unordered list.

Description 

In this project, you need to read a list of number from a given file, which is Unordered_List.txt under Doc Sharing tab. This file includes 1,000,000 numbers, one per line basis.

Write your program to read all numbers from file to an array. Then, 
Write a function to perform a bubble sort on the array.
Wrire a function to perform an insertion on the array.
Also, refer to  http://codepad.org/lpUzqSV1 for the example of clock() function. Using similar structure, you need to measure how many ticks takes each sort algorithm (bubble and insertion). After running each function, print your measurement on the screen.

Report number of ticks in the documentation of your program, such as 

>The bubble sort spent 123 ticks to sort the array
>The insertion sort spent 67 ticks to sort the array

In the second part of this assignment, you need to write a function to search a given number on the unsorted array. First ask the user which number he/she will search.  Then, if your program find the number in the array, output array index, such as "123 found at Array[1111]." If you could not find the number then give an error indicating item is not found.


Notes:

Don’t use unnecessary libraries. clock() function requires <time.h>. You may use lose points because of calling unused libraries.
Commenting in appropriate way will be evaluated. 
Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - Date
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment #11
 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.
  
*/
int main()
{
 
}
      

dropbox01Dropbox Assignment Submission Procedures
To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled Sorting. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


** Hotel Manager
Hotel Manager
Due date: 11:59pm, Friday, 4/11
Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late day (24 hour).
Submission: You need to upload your assignment through eCollege system. You should upload a file named HotelManager.cpp.
Objective: In this assignment you need to demonstrate your skills in 3D array representation, abstraction and manipulation.
 
Description 

Download Hotel.txt  from Doc Sharing section of eCollege. This file includes names of guests at  your hotel. A similar structure of the hotel/dorm was discussed in the class. The hotel is 5-floor building having 10 rooms (2 x 5 or 5 x 2 arrangement)  at each floor.  Write a C++ program to


Define and initialize a 3D array to keep names of all guests.
Given a floor number, print out names of all guests staying at this particular floor.
Print out names of guests that stay in the corner rooms.
Given a name of guest, print out room number (similar to array index). 
Details of the homework will be discussed in the class. 
 
 
Notes:

Don’t use unnecessary libraries. 
Commenting in appropriate way will be evaluated. You may lose 1 (one) point if you don’t comment out your code appropriately.   
Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - Sep 8, 2009
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment #9
 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.
  
*/
int main()
{
 
}
 
      

dropbox01Dropbox Assignment Submission Procedures
To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled HotelManager. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


** Char Frequency
CharFrequency
Due date: Wed, Oct 22, 11:59pm

Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late hour.

Submission: You need to upload your assignment through eCollege system. You should upload a file named CharFrequency.cpp.

Objective: In this assignment, you need to mainly demonstrate your ability in parallel arrays mostly .


Description

Assume that you are given a text file, which can contain up to 200 letters from the set of {A, B, C, D, E}, such as

A 
B B A A D E E E A A
C C D D D D D

In the data file, number of letters in one line can be different than others. Write a C++ program to find 
1) Frequency of each letter
2) The least and most frequent letter.

For the above example, the output should be

A -> 5
B -> 2
C -> 2
D -> 6
E -> 3

The least frequent letter(s) seen 2 times: B, C
The most frequent letter(s) seen 6 times: D

You should use an array / arrays with reasonable initial capacity. 
Don’t use unnecessary libraries, you may use lose points because of calling unused libraries.
Commenting in appropriate way will be evaluated.


Your code should start with comments as seen in following:

// FIRSTNAME LASTNAME  - Feb 3, 2010

// CWID: 123456789

// Compiler: Visual Studio, GNU C++, etc.

// Assignment #3

 

/* This program calculates … or This function takes two int parameters ….

Summarize your code functionality here.

  

*/

int main()

{}

 

Dropbox Assignment Submission Procedures

To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled CharFrequency. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.

* 06 Structs (Records)

** Absolute Frequency
Absolute  Frequency
Due date: Wednesday, Nov 12, 11:59pm

Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late hour.

Submission: You need to upload your assignment through eCollege system. You should upload a file named AbsFre.cpp.

Objective: In this assignment, you need to mainly demonstrate your ability in using structs and stings.


Description

Assume that you are given a text file, which can contain up to 50 numbers or characters. Your task is to write a C++ program to find the quantity of the form of each number / char appeared in this file. The form of a number means positive and negative valued number, or lower- and uppercase letters. 

You need to ask user to enter file path to open. 

For instance, after asking a file path

> Enter file to open: mydata.txt

 5 -9  A -15 -5 54 62 -54 95 -44 5 a C K


Your program should output similar to:

 Number	Positive
 Negative
 5	 2	 1
 9	0	 1
 15	 0	 1
 54	 1	 1
 95	 1	 0
 44	 0	 1
62
1
0


 Char	lower
 Upper
 a	 1	 1
 C	0	 1
 K	 0	 1

In above example, there are 10 numbers and 3 chars in the file. 5 was seen two times as positive, and one time negative. 

You should complete this task using structs. First define your struct , then create an array of structs with reasonable initial capacity.


You should use array(s) of struct, depicted as for (numbers)

Number
Pos
Neg
Number
Pos
Neg
Number
Pos
Neg
Number
Pos
Neg
…..
 
…..
 
…..
 
struct item
{
  ...
  ...
  ...
};

item list[??];


Don’t use unnecessary libraries, you may use lose points because of calling unused libraries.
Commenting in appropriate way will be evaluated.

Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - Feb 3, 2010
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment #3
 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.
  
*/
int main()
{}
Dropbox Assignment Submission Procedures


To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled Absolute Frequency. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


** Sorted Structs
Sorted Structs

Due date: 11:59pm, Nov 23

Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late day (24 hour).
Submission: You need to upload your assignment through eCollege system. You should upload a file named SortedStructs.cpp.
Objective: In this assignment you need to demonstrate your skills in structs, insertion sort, arrays, functions.

Description 

Download  Struct_DB.txt from Doc Sharing section of this course. This file includes 109 lines. First line is a comment line, rest of them (108 lines) are data lines. 

You responsibilities include followings:

Define and initialize a struct to hold each item indicated in one line. See first line of the file for the hints about data types.
Read data from files into your array of structs. 
Display a menu to ask which item will be used in sorting. Sorting the structs will be based on different pieces of data: CID, CNAME, and Time. Use only selection sort. 

A selection code for a int array is below.


 selection 



Notes:

Don’t use unnecessary libraries. 
Commenting in appropriate way will be evaluated. You may lose 1 (one) point if you don’t comment out your code appropriately.   
Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - Sep 8, 2009
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment #9
 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.
  
*/
int main()
{
 
}
      

dropbox01Dropbox Assignment Submission Procedures
To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled SortedStructs. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


** Phone Keys
Phone Keys

 International Standard Key Pad

1	2 
ABC
3 
DEF
4 
GHI
5 
JKL
6 
MNO
7 
PQRS
8 
TUV
9 
WXYZ

0	

Due date: Wednesday, Nov 5, 11:59pm

Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late hour. 

Submission: You need to upload your assignment through eCollege system. You should upload a file named PhoneKeys.cpp. 

Objective: In this assignment, you need to mainly demonstrate your ability in using structs. 


Description

See above figure which shows numbers-letter association used in phone keys. Your task is to 
1- Keep those association in an array of struct, such as 
A,2
B,2
C,2
...
...
...
Z,9
2- Given a three letter combination, find corresponding numbers for the string.

In a menu ask user to enter a three-letter string.

CSI 

Your program should output 274. Similarly, 

ABC should be map to 222 
TOM should be map to 866
BUY should be map to 289

Ask user the strings repeatedly until user enters EXT.  


- Don’t use unnecessary libraries, you may use lose points because of calling unused libraries. 
- Commenting in appropriate way will be evaluated.


Your code should start with comments as seen in following: 

// FIRSTNAME LASTNAME - Feb 3, 2019 

// CWID: 123456789 

// Compiler: Visual Studio, GNU C++, etc. 

// Assignment PhoneKeys 



/* This program calculates … or This function takes two int parameters …. 

Summarize your code functionality here. 


*/ 

int main() 

{} 

Dropbox Assignment Submission Procedures 

To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled Assignment PhoneKeys. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button. 



** Struct with Functions
StructWFuntions

Due date: 11:59pm (noon), Nov 6

Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late hour.
Submission: You need to upload your assignment through eCollege system. You should upload a file named StructWFunctions.cpp.
Objective: In this assignment you need to demonstrate your skills in structs and functions.

Description 

Assume you want to model "house", which can have attributes, such as address, owner, lot_size, and year_built. Model your house struct with at least three (3) attributes. Then

-Define a function void initHouse (house &) that fills a house struct with some default values.
-Define a function bool compareHouse(house, house) that compares two houses and returns true if they are same, or false if they are different.

In you main function create two imaginary house variables and show the usage of these two functions in your code.

Notes:

Don’t use unnecessary libraries. 
Commenting in appropriate way will be evaluated. You may lose 1 (one) point if you don’t comment out your code appropriately.   
Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - Sep 8, 2009
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment StructWFunctions
 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.
  
*/
int main()
{
 
}
      

dropbox01Dropbox Assignment Submission Procedures
To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled StructWFunctoins. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


** Cricket World Cup

CricketWorldCup

Due date: 11:59pm, Saturday, Apr 26
Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late day (24 hour).
Submission: You need to upload your assignment through eCollege system. You should upload a file named Cricket.cpp.
Objective: In this assignment you need to demonstrate your skills in structs, selection sort, arrays, functions..

Description 

Download  Cricket World Cup 2011.txt from Doc Sharing section of the course. This file includes 49 match schedules of World Cup. First two lines are comment lines, and indicated by # at their first character. Rest of them (49 lines) are data lines. 

You responsibilities include followings:
Define and initialize a struct to hold each item indicated in one line.
Read data from files into your array of structs.
To do this, write a function takes a string STR (one data line from the file) and returns a struct filled with the data given in STR. 
Sorting the structs based on different pieces of data, Date, Match, Venue, Time. Display a menu to ask which item will be used in sorting.
Write a function takes a parameter as a indicator of sort item, then print out  sorted items. Use selection sort (given below for arrays).



 selection 



Notes:

Don’t use unnecessary libraries. 
Commenting in appropriate way will be evaluated. You may lose 1 (one) point if you don’t comment out your code appropriately.   
Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - Sep 8, 2013
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment #9
 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.
  
*/
int main()
{
 
}
      

dropbox01Dropbox Assignment Submission Procedures
To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled CricketWorldCup. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


* 07 Pointers, Dynamic Memory

** Arrow Operator (Intro to Pointers)
Intro to Pointers
Due date: Wednesday, Apr 3, 11:30am

Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late hour.

Submission: You need to upload your assignment through eCollege system. You should upload a file named IntPointer.cpp.

Objective: In this assignment, you need to mainly demonstrate your ability in using pointers with basic data types and structs.

Description

You need to define a float variable and a struct of three components. Later, define a pointer data type for float and struct variables. Make those pointer regularly show related variables. Then, demonstrate the followings by printing out:
Address of the float variable and value of float pointer are same
Address of the struct variable and value of struct pointer are same
In the second phase of the program, Use -> and . operators with your struct to show that  a statement such as 
if (.... -> ....  == .... . .....  ) returns TRUE. 

Don’t use unnecessary libraries, you may use lose points because of calling unused libraries.
Commenting in appropriate way will be evaluated.

Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - Feb 3, 2010
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment #14
 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.
  
*/
int main()
{}
Dropbox Assignment Submission Procedures


To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled IntroPointers. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.


** Word Hunter
Word Hunter
Due date: 11:59pm, Friday, Nov 21
Grade: You will earn 100 points if you return your assignment complete and in time. You will lose 30 points for each late day (24 hour).

Submission: You need to upload your assignment through eCollege system. You should upload a file named WordHunter.cpp.

Objective: In this assignment you need to demonstrate your skills in menu design, using functions (predefined and user), file operations, dynamic memory allocation, formatted printing and char arrays.

Description 

Your aim is to design program to find/list  specified words from English dictionary.  Your source file is Ordered_Word_list.txt (this file is reachable under Doc Sharing).  First line of this file has descriptive data, which says how many words listed in this file. List of words starts at second line, and goes until at the end of file one-per-line basis. Use a dynamic array to hold all words from the file.
A user can list words based on length and substring.  Therefore you will ask user to enter two parameters.
- What is the length of word?
- What substring should be appeared in the word?
For instance, when user enters 8 and "you", your program should print out these words from dictionary.
embryous
fooyoung
joyously
unjoyous
youngish
younglet
yourself
youthful
youthily
youwards

The programming steps are follows:
- Dynamically create an array to keep words in a string array. 
- Read words from the file and store them in dynamic array.
- Design a menu to ask user search parameters (length and substring).
- Exit the menu if user enter 0 as a length of word.

Notes:
Don’t use unnecessary libraries. 
Commenting in appropriate way will be evaluated. You may lose 3 (three) points if you don’t comment out your code appropriately.  
Your code should start with comments as seen in following:
// FIRSTNAME LASTNAME  - April, 2010
// CWID: 123456789
// Compiler: Visual Studio, GNU C++, etc.
// Assignment #19
 
/* This program calculates … or This function takes two int parameters ….
Summarize your code functionality here.
  
*/
int main()
{
 
}
      

dropbox01Dropbox Assignment Submission Procedures
To submit to the Dropbox, click on the Dropbox tab at the top of this course content frame. Click on the Submit an Assignment link. Choose the Dropbox Basket titled Word Hunter. Click the Add Attachments button to browse for the assignment document on your computer that you would like to submit. After attaching this document, you may add comments to your instructor in the Comments field if you wish, then click the Submit button.

